# equivalent of travis test_user_install stage (appveyor doesn't have stages)

environment:
  matrix:
    - PY: "3.7"
      PYTHON: "C:\\Python37-x64"
      CONDA: "C:\\Miniconda37-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyctdev && doit ecosystem_setup"

build: off

test_script:
  - "copy dodo.py %TMP% && copy tox.ini %TMP% && cd %TMP%"
  - "doit test_user_install_part1"
  - "activate holoviz-tutorial"
  - "doit test_user_install_part2"
