environment:
  global:
    CHANS_DEV: "-c defaults -c pyviz/label/dev"  # this order matters because we're using strict channel priority
    PIN: "--pin-deps"
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda config --set always_yes True"
  - "conda install -c pyviz/label/dev pyctdev && doit ecosystem_setup"
  - "conda config --set path_conflict warn"
  - "conda config --set channel_priority strict"  # this makes the conda solver **way** faster
  - "doit env_create --name=holoviz --python=%PY%"
  - "activate holoviz"
  - "doit develop_install %CHANS_DEV% --all-extras"
  - "doit env_capture"

build: off

test_script:
  - "xcopy examples\\data\\.data_stubs examples\\data /E /f /i"  # HACK until pyct is fixed
  - "holoviz fetch-data --path=examples --use-test-data"
  - "pip install nbsmoke"  # for some reason the extension isn't registered properly with pytest
  - "doit test_all"
  - "holoviz clean-data --path=examples"
