environment:
  global:
    CHANS_DEV: "-c pyviz/label/dev"
    PIN: "--pin-deps"
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyctdev && doit ecosystem_setup"
  - "doit env_create --name=pyviz --python=%PY%"
  - "activate pyviz"
  - "doit develop_install %CHANS_DEV% %PIN% --all-extras"
  - "doit env_capture"

build: off

test_script:
  # (same as python pyviz/download_sample_data.py, but for quick tests)
  - "move examples/data/nyc_taxi_50k.parq examples/data/nyc_taxi_wide.parq"
  - "pyviz fetch-data --path=examples"
  - "doit test_examples"
