name: pyviz
channels:
  - pyviz
  - defaults
dependencies:
  # 
  # Versions for pyviz-maintained packages pinned to ensure mutual compatibility
  # 
  - bokeh=0.13.0
  - holoviews=1.10.7
  - geoviews=1.5.2
  - hvplot=0.2.1
  - datashader=0.6.6
  - param=1.6.1
  - paramnb=2.0.3
  - parambokeh=0.2.2
  # 
  # Direct dependencies for package installation
  # 
  - yaml
  - requests
  # 
  # Direct dependencies of most or all the tutorials
  # 
  - python>=3.6,<3.7 # Pinned in case of unknown future or past compatibility issues
  - ipython=5        # Pinned to avoid tab-completion issue in ipython=6
  - numpy=1.13
  - notebook>=5.4    # Pinned to avoid rate limiting for large images with notebook=5.0
  - dask=0.18.1      # Pinned for future compatibility
  - jupyter
  - pandas
  - xarray
  # 
  # Directly imported dependencies of certain specialized tutorials
  # 
  - networkx         # Required for some graph examples
  - cartopy          # Required for some GeoViews examples
  - streamz=0.3.0    # Pinned due to StreamingDataFrame name change in 0.3.0
  - scikit-image     # Required for datashader graphs
  - geopandas        # Required for geo data examples
  # 
  # Indirect dependencies of our direct dependencies
  # 
  - selenium         # Required for exporting Bokeh plots to PNG
  - phantomjs        # Required for exporting Bokeh plots to PNG
  - netcdf4          # Required for reading .nc files
  - fastparquet      # Required for reading Parquet files
  - python-snappy    # Required for reading snappy-compressed Parquet files
  - pytest>=3.2      # Required by? Pinned to avoid installation problems on Windows with 3.1?
  - ipywidgets=7     # Required for paramnb. Pinned to avoid JS errors for widgets
  - cffi             # Unstated dependency of fastparquet?
  - tornado=4.5.3    # Required for Jupyter notebook and bokeh server
