name: holoviz-tutorial
channels:
  - pyviz/label/dev
dependencies:
  - python=3.8
  - numpy
  - pandas<1.3
  - dask
  - xarray
  - notebook
  - matplotlib
  - ipympl
  - bokeh=2.3.3
  - datashader
  - param
  - netcdf4
  - fastparquet
  - jupyterlab
  - fsspec=0.9.0
  - hvplot=0.8.0a7
  - panel=0.12.0rc10
  - holoviews=1.14.5a6
  - anaconda-project
