name: docs

on:
  push:
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'
    #   - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]+'
    #   - 'v[0-9]+.[0-9]+.[0-9]+b[0-9]+'
    #   - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build_docs:
    name: Documentation
    runs-on: 'ubuntu-latest'
    timeout-minutes: 120
    defaults:
      run:
        shell: bash -l {0}
    env:
      DESC: "Documentation build"
      MPLBACKEND: "Agg"
      MOZ_HEADLESS: 1
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "100"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: conda setup
        run: |
          conda update -n base -c defaults conda
          conda create -n test-environment -c pyviz/label/dev -c conda-forge python=3.9 
      - name: doit develop_install
        run: |
          eval "$(conda shell.bash hook)"
          conda activate test-environment
          conda list
          conda install anaconda-project
          cd examples
          anaconda-project prepare
          cd ..
          conda activate examples/envs/default
          pip install nbsite --pre
          pip install pydata_sphinx_theme
          pip install --no-deps --no-build-isolation -e .
      - name: generate rst
        run: |
          eval "$(conda shell.bash hook)"
          conda activate examples/envs/default
          nbsite generate-rst --org holoviz --project-name holoviz --offset 1 --skip envs
      - name: build docs
        run: |
          eval "$(conda shell.bash hook)"
          conda activate examples/envs/default
          nbsite build --what=html --output=builtdocs --org holoviz --project-name holoviz
      - name: git status
        run: |
          git status
          git diff
      # - name: Deploy dev
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: (contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc'))
      #   with:
      #     personal_token: ${{ secrets.ACCESS_TOKEN }}
      #     external_repository: pyviz-dev/holoviz
      #     publish_dir: ./builtdocs
      #     force_orphan: true
      # - name: Deploy main
      #   if: (!(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./builtdocs
      #     cname: holoviz.org
      #     force_orphan: true
